### ISSUE TITLE
Add manifest example to docs

### ISSUE THREAD

**Issue by ai** [usmanyunusov/webpack-webmanifest-plugin#1]
To explain how to specify paths to images

**Comment by usmanyunusov** [comment]
Supplemented the documentation: https://github.com/usmanyunusov/webpack-webmanifest-plugin/blob/master/README.md

**Comment by ai** [comment]
It is better to replace `require("./manifest.webmanifest");` example to some more real HTML template

**Comment by usmanyunusov** [comment]
Added real HTML template 
https://github.com/usmanyunusov/webpack-webmanifest-plugin/commit/001f44f051084de1d55212d6aac091111d669e31#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R24
