### ISSUE TITLE
Reduce npm package size

### ISSUE THREAD

**Issue by ai** [usmanyunusov/webpack-webmanifest-plugin#3]
1. Add `clean-publish` and release package by `npx clean-publish` instead of `npm publish`
2. Add `.npmignore` to avoid adding `test/` (current `src/`) to npm package

**Comment by usmanyunusov** [comment]
Added `clean-publish` and `.npmignore` in https://github.com/usmanyunusov/webpack-webmanifest-plugin/commit/279d55e7967e60b8efcf251eb4cafa7666ec86c7
